#
# SPDX-FileCopyrightText: 2021 William Swartzendruber <wswartzendruber@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0
#

[workspace]
members = [
    "pgsmod",
    "pgsdump",
    "pgstest",
    "pgs",
]
